version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
      - image: circleci/postgres:10.5
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gamesapi

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          key: restful-{{ checksum "requirements.txt" }}
      - run:
          name: install depedencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: migrate db
          command: |
            . venv/bin/activate
            python gamesapi/manage.py migrate
