version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
      - image: circleci/postgres:10.5

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install depedencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: migrate db
          command: |
            python gamesapi/manage.py migrate
